### ISSUE TITLE
Wrong value at column use_cpu

### ISSUE THREAD

**Issue by ArtemNegriXMLShop** [XMLSHOP/Laravel-Queue-Monitor#19]
Wrong value at column `use_cpu`.
<img width="74" alt="Screenshot 2022-12-17 at 14 06 44" src="https://user-images.githubusercontent.com/109627141/208243363-9b16d752-7fcb-4436-b9b6-ce493f7faff2.png">
<img width="75" alt="Screenshot 2022-12-17 at 14 06 34" src="https://user-images.githubusercontent.com/109627141/208243365-7b69446e-8d63-49bb-b1f5-fa51d2530259.png">

Why are they negative?

**Comment by pkulbida** [comment]
Updated
