### ISSUE TITLE
Scheduler monitoring wrongly repeats at `command`

### ISSUE THREAD

**Issue by ArtemNegriXMLShop** [XMLSHOP/Laravel-Queue-Monitor#20]
Issue:
As soon as command is triggering by scheduler, we also see it in x_monitor_command. 

Probably make sense to use listener something like that way:
Event::listen(CommandStarting::class, BackgroundCommandListener::class);

https://github.com/spatie/laravel-schedule-monitor
src/EventHandlers/BackgroundCommandListener.php
<img width="1115" alt="Screenshot 2022-12-17 at 16 48 43" src="https://user-images.githubusercontent.com/109627141/208250116-f131f587-e032-4bc8-ab93-74a2e821fe07.png">

<img width="1109" alt="Screenshot 2022-12-17 at 16 48 36" src="https://user-images.githubusercontent.com/109627141/208250106-104fdc42-441b-4792-9798-0fbbd5aa0629.png">

**Comment by pkulbida** [comment]
Petro K, [12/19/2022 5:27 PM]
В общем заглушить не получится

Petro K, [12/19/2022 5:27 PM]
комманды из щедуллера запускаются в отдельных процессах

Petro K, [12/19/2022 5:28 PM]
Process::fromShellCommandline

Petro K, [12/19/2022 5:28 PM]
и для каждого процесса подымается отдельный инстанс консольного приложения и соответственно листенеры для команд асайнятся на ивенты

Petro K, [12/19/2022 5:28 PM]
и мы не знаем что было перед этим процессом и тд

Petro K, [12/19/2022 5:30 PM]
Process is a thin wrapper around proc_* functions to easily
 * start independent PHP processes.

Petro K, [12/19/2022 5:31 PM]
Symfony\Component\Process
