### ISSUE TITLE
If command has an error, it doesn't get failed as scheduler task

### ISSUE THREAD

**Issue by ArtemNegriXMLShop** [XMLSHOP/Laravel-Queue-Monitor#21]
If command has an error, it doesn't get failed as scheduler task.

Have to be managed somhow.

**Comment by pkulbida** [comment]
По той же причине , что и https://github.com/XMLSHOP/Laravel-Queue-Monitor/issues/20

Process is a thin wrapper around proc_* functions to easily start independent PHP processes.
Symfony\Component\Process\Process::fromShellCommandline

Для каждого процесса/комманды подымается отдельный инстанс консольного приложения - процесс имеет аутпут, но никакой ексепшин не может быть возвращен в родительский процесс

Процесс выброса ScheduledTaskFailed определен в методе \Illuminate\Console\Scheduling\ScheduleRunCommand::runEvent  - ScheduledTaskFailed  в потоке логики может быть выброшен при некорректной обработке события ScheduledTaskFinished

**Comment by ArtemNegriXMLShop** [comment]
Пофикшено.
